port: 80

siteName: Tanuki BBS
siteSlogans: []
siteRules: []

adminPassword: 
adminPostOnly: false

postCooldown: 30
loginCooldown: 10

maxPostsPerPage: 5
maxPages: 10
maxBumps: 50

maxNameSize: 20
maxSubjectSize: 32
maxCommentSize: 300
maxUploadSize: 4
